--- 
author: "Dev Menon"
author_image: /assets/images/images.jpg
baseurl: ""
cover: /assets/images/unknown.jpg
description: "A blog for progress. Anything and everything"
email: dev.n.menon@gmail.com
gems: 
  - jemoji
highlighter: pygments
logo: /assets/images/images.jpg
markdown: redcarpet
name: "Dev Menon"
paginate: 5
social: 
  - 
    ? "icon:	github url:	https://github.com/dnamenon desc: share_url"
    : ~
    share_link: ~
    share_title: ~
title: DNM
url: ""
baseurl: "dnamenon.github.io"


# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
 #   share_url: http://twitter.com/share
 #   share_title: ?text=
  #  share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dnamenon
    desc:	
    share_url:
    share_title:
    share_link:

# - icon:	google-plus
 #   url:	https://google.com/dev.n.menon
  #  desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
